services:
  resumeparsing:
    build:
      context: .
      dockerfile: resumeParsing/Dockerfile
    container_name: resume-parsing
    image: resumeparsing:latest
    environment:
      - UPLOADS_DIR=/app/data/uploads
      - CHROMA_DIR=/app/data/chroma
      - CHROMA_COLLECTION=resumes
      - EMBED_MODEL=sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
      - CHUNK_SIZE=800
      - CHUNK_OVERLAP=120
    ports:
      - "8000:8000"
    volumes:
      - ./resumeParsing/app:/app/app:ro
      - ./data/uploads:/app/data/uploads
      - ./data/chroma:/app/data/chroma
    restart: unless-stopped

  backend:
    image: node:20-bullseye
    working_dir: /app
    container_name: backend
    command: sh -c "apt-get update && apt-get install -y --no-install-recommends ffmpeg && npm install && npm run dev"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/ai_vtb?schema=public
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - IS_PROXY_API_ENABLED=${IS_PROXY_API_ENABLED}
      - IS_IMAGE_GENERATION_ENABLED=${IS_IMAGE_GENERATION_ENABLED}
      - PROXY_API_KEY=${PROXY_API_KEY}
      - RAG_API_URL=http://resumeparsing:8000
      - TTS_URL=${TTS_URL:-http://tts:8081}
      - EMOTIONS_URL=${EMOTIONS_URL:-http://emotions:5000}
      - BOT_API_URL=http://bot:8000
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    depends_on:
      - resumeparsing
      - postgres
    restart: unless-stopped

  tts:
    build:
      context: ./tts
      dockerfile: Dockerfile
    container_name: tts
    image: tts:latest
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY_TTS}
      - YANDEX_IAM_TOKEN=${YANDEX_IAM_TOKEN}
      - YANDEX_API_KEY=${YANDEX_API_KEY}
    ports:
      - "8081:8081"
    restart: unless-stopped

  emotions:
    build:
      context: ./emotions-parser
      dockerfile: Dockerfile
    container_name: emotions
    image: emotions-parser:latest
    environment:
      - HF_HOME=/app/hf_cache
      - TRANSFORMERS_CACHE=/app/hf_cache
      - HUGGINGFACE_HUB_CACHE=/app/hf_cache
      - YANDEX_IAM_TOKEN=${YANDEX_IAM_TOKEN}
      - YANDEX_API_KEY=${YANDEX_API_KEY}
    # - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
    ports:
      - "5000:5000"
    restart: unless-stopped

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: telegram-bot
    image: telegram-bot:latest
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - BACKEND_API_URL=http://backend:3000
    ports:
      - "8002:8000"
    depends_on:
      - backend
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    image: frontend-nginx:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    volumes:
      - /srv/certbot/www:/var/www/certbot

  postgres:
    image: postgres:16-alpine
    container_name: pg-dev
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ai_vtb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin-dev
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5051:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  node_modules_cache:
  backend_node_modules:
  pg_data:

