services:
  resumeparsing-dev:
    build:
      context: .
      dockerfile: resumeParsing/Dockerfile
    container_name: resume-parsing-dev
    image: resumeparsing:latest
    environment:
      - UPLOADS_DIR=/app/data/uploads
      - CHROMA_DIR=/app/data/chroma
      - CHROMA_COLLECTION=resumes
      - EMBED_MODEL=sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
      - CHUNK_SIZE=800
      - CHUNK_OVERLAP=120
    ports:
      - "8000:8000"
    volumes:
      - ./resumeParsing/app:/app/app:ro
      - ./data/uploads:/app/data/uploads
      - ./data/chroma:/app/data/chroma
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: pg-dev
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ai_vtb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin-dev
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5051:80"
    depends_on:
      - postgres
    restart: unless-stopped

  backend-dev:
    image: node:20-bullseye
    working_dir: /app
    container_name: backend-dev
    command: sh -c "apt-get update && apt-get install -y --no-install-recommends ffmpeg && npm install && npm run dev"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/ai_vtb?schema=public
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - IS_PROXY_API_ENABLED=${IS_PROXY_API_ENABLED}
      - IS_IMAGE_GENERATION_ENABLED=${IS_IMAGE_GENERATION_ENABLED}
      - PROXY_API_KEY=${PROXY_API_KEY}
      - RAG_API_URL=http://resumeparsing-dev:8000
      - TTS_URL=${TTS_URL | http://tts-dev:8081}
      - EMOTIONS_URL=${EMOTIONS_URL | http://emotions-dev:5000}
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    depends_on:
      - resumeparsing-dev
      - postgres
    restart: unless-stopped

  frontend-dev:
    image: node:20-alpine
    working_dir: /app
    container_name: frontend-dev
    command: sh -c "npm install && npm run dev -- --host"
    volumes:
      - ./frontend:/app
      - node_modules_cache:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "5174:5173"
    depends_on:
      - resumeparsing-dev
    restart: unless-stopped

  tts-dev:
    build:
      context: ./tts
      dockerfile: Dockerfile
    container_name: tts-dev
    image: tts:latest
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY_TTS}
    command: sh -c "uvicorn app:app --host 0.0.0.0 --port 8081 --reload"
    volumes:
      - ./tts:/app
    ports:
      - "8081:8081"
    restart: unless-stopped

  emotions-dev:
    build:
      context: ./emotions-parser
      dockerfile: Dockerfile
    container_name: emotions-dev
    image: emotions-parser:latest
    environment:
      - HF_HOME=/app/hf_cache
      - TRANSFORMERS_CACHE=/app/hf_cache
      - HUGGINGFACE_HUB_CACHE=/app/hf_cache
    # - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
    volumes:
      - ./emotions-parser:/app
    ports:
      - "5000:5000"
    command: sh -c "python app.py"
    restart: unless-stopped

# transcriber-dev:
#   build:
#     context: ./transcriber
#     dockerfile: Dockerfile
#   container_name: transcriber-dev
#   image: transcriber:latest
#   environment:
#     - HF_HOME=/app/hf_cache
#     - TRANSFORMERS_CACHE=/app/hf_cache
#     - HUGGINGFACE_HUB_CACHE=/app/hf_cache
#   volumes:
#     - ./transcriber:/app
#   ports:
#     - "5544:5544"
#   command: sh -c "uvicorn main:app --host 0.0.0.0 --port 5544 --reload"
#   restart: unless-stopped

volumes:
  node_modules_cache:
  backend_node_modules:
  pg_data:
